### ISSUE TITLE
Discovery: Use Django LocaleMiddleware instead of django-lang-pref-middleware

### ISSUE THREAD

**Issue by sarina** [openedx/django-lang-pref-middleware#264]
My recollection is this custom middleware was written prior to Django having its own locale middleware, or at least, the Django native middleware didn't do what we want.

The last time this code was meaningfully updated was in 2014, [when it was extracted from edx-platform](https://github.com/openedx/django-lang-pref-middleware/commit/6f873db33ca32f924dc7004a58bf3845f4f55605). We should take a step back and investigate if there are Django native patterns around localization we should follow, to bring our project up to Django standards and avoid maintenance burden of custom middleware.

Can we replace this middleware with [Django's LocaleMiddleware](https://github.com/django/django/blob/stable/4.2.x/django/middleware/locale.py)? [Docs are here](https://docs.djangoproject.com/en/5.1/ref/middleware/#django.middleware.locale.LocaleMiddleware).

**Comment by sarina** [comment]
@feanil I don't see an Aximprovements team project to add this to

**Comment by feanil** [comment]
I've added it.

**Comment by irtazaakram** [comment]
Hey @sarina, I couldn’t find where this package is used in the [Open edX repositories](https://github.com/search?q=org%3Aopenedx+django-lang-pref-middleware&type=code). The only usage I found was in this edX repository: [edx-analytics-dashboard](https://github.com/edx/edx-analytics-dashboard/blob/b180478255911345b91399a90ac3f254dfff02de/analytics_dashboard/core/middleware.py#L9).
